spring.h2.console.enabled=false

spring.datasource.url=jdbc:mysql://db:3306/brainwave_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=brainwave_user
spring.datasource.password=brainwave_pass

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect